"""
PowerShell Command Generation for ASR Rules
"""

from typing import Dict, List, Optional, Tuple
from src.asrdata import ASR_RULES, ASRRule

class PSGenerator:
    """Generate PowerShell commands for ASR rule management"""
    
    MODE_MAP = {
        "Block": "Enabled",
        "Audit": "AuditMode",
        "Warn": "Warn",
        "Disable": "Disabled",
    }
    
    @staticmethod
    def generate_rule_command(
        rule_ids: List[str], 
        mode: str, 
        exclusions: Optional[List[str]] = None
    ) -> str:
        """
        Generate a PowerShell command for setting ASR rules
        
        Args:
            rule_ids: List of rule GUIDs
            mode: "Block", "Audit", "Warn", or "Disable"
            exclusions: Optional list of exclusion paths
            
        Returns:
            PowerShell command string
        """
        if not rule_ids:
            return ""
        
        action = PSGenerator.MODE_MAP.get(mode, "Enabled")
        
        # Join rule IDs with comma
        rule_string = ", ".join([f'"{rule_id}"' for rule_id in rule_ids])
        
        # Build base command
        command = f'Set-MpPreference -AttackSurfaceReductionRules_Ids @({rule_string}) -AttackSurfaceReductionRules_Actions {action}'
        
        return command
    
    @staticmethod
    def generate_exclusion_command(
        exclusion_paths: List[str],
        rule_id: Optional[str] = None
    ) -> str:
        """
        Generate exclusion command(s)
        
        Args:
            exclusion_paths: List of paths to exclude
            rule_id: Optional - if provided, creates per-rule exclusion
            
        Returns:
            PowerShell command string
        """
        if not exclusion_paths:
            return ""
        
        # Escape paths for PowerShell
        escaped_paths = [f'"{path}"' for path in exclusion_paths]
        path_string = ", ".join(escaped_paths)
        
        if rule_id:
            # Per-rule exclusion
            command = f'Set-MpPreference -AttackSurfaceReductionRules_Ids "{rule_id}" -AttackSurfaceReductionOnlyExclusions @({path_string})'
        else:
            # Global exclusion
            command = f'Set-MpPreference -AttackSurfaceReductionOnlyExclusions @({path_string})'
        
        return command
    
    @staticmethod
    def generate_batch_commands(
        config: Dict[str, Dict]
    ) -> Tuple[List[str], List[str]]:
        """
        Generate multiple commands from a configuration dictionary
        
        Args:
            config: Dict mapping rule GUID to {"mode": "Block|Audit|Warn|Disable", "exclusions": [...]}
            
        Returns:
            Tuple of (main_commands, exclusion_commands)
        """
        main_commands = []
        exclusion_commands = []
        mode_grouping = {"Block": [], "Audit": [], "Warn": [], "Disable": []}
        
        for rule_id, settings in config.items():
            mode = settings.get("mode", "Block")
            exclusions = settings.get("exclusions", [])
            
            # Group rules by mode
            if mode in mode_grouping:
                mode_grouping[mode].append(rule_id)
            
            # Generate per-rule exclusions if specified
            if exclusions:
                exclusion_cmd = PSGenerator.generate_exclusion_command(exclusions, rule_id)
                if exclusion_cmd:
                    exclusion_commands.append(exclusion_cmd)
        
        # Generate mode-grouped commands
        for mode, rule_ids in mode_grouping.items():
            if rule_ids:
                cmd = PSGenerator.generate_rule_command(rule_ids, mode)
                if cmd:
                    main_commands.append(cmd)
        
        return main_commands, exclusion_commands
    
    @staticmethod
    def generate_full_script(
        config: Dict[str, Dict],
        include_header: bool = True,
        include_verification: bool = True
    ) -> str:
        """
        Generate a complete, ready-to-run PowerShell script
        
        Args:
            config: Configuration dictionary
            include_header: Include comments and requires statement
            include_verification: Include Get-MpPreference command to verify
            
        Returns:
            Complete PowerShell script
        """
        lines = []
        
        if include_header:
            lines.extend([
                "# Attack Surface Reduction (ASR) Configuration Script",
                "# Generated by ASRGEN",
                "# This script requires administrator privileges",
                "#",
                "# Before running, ensure you have reviewed the rules and understand their impact.",
                "",
                "#Requires -RunAsAdministrator",
                "",
            ])
        
        main_commands, exclusion_commands = PSGenerator.generate_batch_commands(config)
        
        if main_commands or exclusion_commands:
            lines.append("# Set ASR Rules")
            lines.extend(main_commands)
            lines.append("")
        
        if exclusion_commands:
            lines.append("# Configure Exclusions")
            lines.extend(exclusion_commands)
            lines.append("")
        
        if include_verification:
            lines.extend([
                "# Verify the configuration",
                "Write-Host 'ASR Configuration Summary:'",
                "$asr = Get-MpPreference | Select-Object AttackSurfaceReductionRules_Ids, AttackSurfaceReductionRules_Actions",
                "$asr | Format-List",
            ])
        
        return "\n".join(lines)
    
    @staticmethod
    def generate_view_command() -> str:
        """Generate command to view current ASR configuration"""
        return "Get-MpPreference | Select-Object -ExpandProperty AttackSurfaceReductionRules_Ids"
    
    @staticmethod
    def generate_remediate_command(rule_id: str) -> str:
        """Generate command to disable a specific rule"""
        return f'Set-MpPreference -AttackSurfaceReductionRules_Ids "{rule_id}" -AttackSurfaceReductionRules_Actions Disabled'


def simplify_config_for_display(config: Dict[str, Dict]) -> Dict[str, any]:
    """Convert config to human-readable format for preview"""
    summary = {
        "block": [],
        "audit": [],
        "warn": [],
        "disabled": [],
        "exclusions": {}
    }
    
    for rule_guid, settings in config.items():
        rule = ASR_RULES.get(rule_guid)
        rule_name = rule.name if rule else f"Unknown ({rule_guid})"
        mode = settings.get("mode", "Block").lower()
        
        if mode == "block":
            summary["block"].append(rule_name)
        elif mode == "audit":
            summary["audit"].append(rule_name)
        elif mode == "warn":
            summary["warn"].append(rule_name)
        elif mode == "disable":
            summary["disabled"].append(rule_name)
        
        exclusions = settings.get("exclusions", [])
        if exclusions:
            summary["exclusions"][rule_name] = exclusions
    
    return summary
