name: Compile and Release Binary

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile C++ code
      run: |
        cd src
        cl /EHsc /W4 /Fe:lsass_ASR_test.exe lsass_test.cpp
        Move lsass_ASR_test.exe ../

    - name: Create Release and Upload Binary
      uses: softprops/action-gh-release@v1
      with:
        files: lsass_ASR_test.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
