name: Release Workflow

on:
  workflow_run:
    workflows: ["Generate ASR Atomic Test Binaries"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - name: Download the Compiled Binary
      uses: actions/download-artifact@v2
      with:
        name: lsass_ASR_test
    - name: Create Release and Upload Binary
      uses: softprops/action-gh-release@v1
      with:
        files: lsass_ASR_test.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
